name: flutter_flex_frame
description: A Flutter Adaptive Framework Demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 路由管理
  go_router: ^12.1.3
  
  # 依赖注入
  get_it: ^7.6.4
  
  # 状态管理
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0
  
  # UI组件
  cupertino_icons: ^1.0.6
  flutter_adaptive_scaffold: ^0.1.7
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  
  # 国际化
  easy_localization: ^3.0.3
  
  # 工具
  logger: ^2.0.2+1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Code generation
  build_runner: ^2.4.7
  mobx_codegen: ^2.4.0
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  melos: ^6.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
