name: flutter_rss_reader
description: "A Flutter RSS reader with responsive layouts"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State Management
  mobx: ^2.3.0
  flutter_mobx: ^2.3.0
  # Dependency Injection
  get_it: ^7.7.0
  # Routing
  go_router: ^13.0.1
  # Localization
  easy_localization: ^3.0.3
  # RSS Parser
  dart_rss: ^3.0.1
  # HTTP Client
  dio: ^5.4.0
  # HTML Rendering
  flutter_html: ^3.0.0-beta.2
  # Storage
  shared_preferences: ^2.2.2
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.3
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^6.3.0
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/translations/
