name: flutter_rss_reader
description: "A Flutter RSS reader with responsive layouts"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State Management
  mobx: ^2.3.0
  flutter_mobx: ^2.3.0
  # Dependency Injection
  get_it: ^8.0.3
  # Routing
  go_router: ^14.6.3
  # Localization
  easy_localization: ^3.0.3
  # HTML Rendering
  flutter_html: ^3.0.0-beta.2
  # Storage
  shared_preferences: ^2.2.2
  # Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.8.3
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^6.3.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  drift_dev: ^2.14.1
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/translations/
